[build]
  functions = "widget/functions"

[dev]
  functions = "widget/functions"


[[headers]]
  for = "/.widget/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
