[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"


[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"